#该样例请复制两份副本并命名为dev与prod
webSite: http://localhost
db:
  mysql:
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'root',
    database: 'databse',
    charset: 'utf8mb4',
    timezone: '+08:00',
    synchronize: true, #生产环境请关闭自动同步，这很重要！
    autoLoadEntities: true,
    debug: false,
    logging: false,

jwt:
  secret: 'Self setting',
  signOptions:
    expiresIn: '7d',
  global: true,

oss:
  accessKeyId: 'accessKeyId',
  accessKeySecret: 'accessKeySecret',
  endpoint: 'endpoint', #url在概况能看到
  bucket: 'bucket', #是名字不是url
  region: 'region', #oss-国家-地区，oss-cn-guangzhou，好像一定要这样写
  internal: true #是否使用内网
  secure: true #是否使用https
  #下面看情况，如果不需要替换为自定义域名就不用管
  cname: false
  ossUrl: https://your-oss-domain.com #你oss的默认域名
  cnameUrl: https://your-custom-domain.com #你的自定义域名
cdn:
#如果你的oss使用cdn，请开启；通常情况下使用cdn加速oss，oss也会使用自定义域名。但是这个时候请求资源就
#不再通过oss了，而是需要鉴权cdn url。如果设置为true，在获取oss鉴权链接时会使用cdn鉴权方法返回cdn url
#注意：如果cdn没有开启url鉴权你的oss私有会通过cdn变成公共读，建议打开
  useCdn: false
  secret: 123abc
  cdnUrl: https://your-cdn-domain.com #通常下跟你的oss自定义域名一致

#用于推送消息，可以在这里生成https://vapidkeys.com/ 或其他方法生成
subscribeNotification: 
  publicKey: '',
  privateKey: '',

mail:
  host: smtp.office365.com
  port: 587
  secure: false #是否开启ssl
  starttls: true #是否开启starttls,如果要开启这个需要把secure设置为false
  auth:
    user: your-email@example.com
    password: your-email-password
  from: 发件人名字 <your-email@example.com>